"""Default configuration values for LLM DAG Optimizer."""

# Algorithm Selection
DEFAULT_ALGORITHM = "fptas"  # Options: "fptas", "moqo"

# Data Configuration
DEFAULT_LEVEL = 2
DEFAULT_QUERY_TOKENS = 215
DEFAULT_BLENDING_PROMPT_TOKENS = 26
DEFAULT_CONTEXT_TOKENS = 39

# Problem Configuration
DEFAULT_MAX_NODES = 5
DEFAULT_MODELS = [0, 1, 2, 3, 4, 5]

# FPTAS Configuration
DEFAULT_EPSILON = 0.05
DEFAULT_PRUNING_ENABLED = True
DEFAULT_ALLOW_EMPTY_PREDS = True
DEFAULT_EXTRACT_ONLY_ADMISSIBLE = True

# MOQO Configuration
DEFAULT_POPULATION_SIZE = 200
DEFAULT_GENERATIONS = 200
DEFAULT_CROSSOVER_RATE = 0.9
DEFAULT_ADD_NODE_PROB = 0.1
DEFAULT_FLIP_EDGE_PROB = 0.3
DEFAULT_MODEL_MUTATION_PROB = 0.2
DEFAULT_GENOTYPE_DEDUP = True

# Evaluation Configuration
DEFAULT_FUZZY_ENABLED = False
DEFAULT_EXACT_ENABLED = True
DEFAULT_FUZZY_THRESHOLD = 0.70
DEFAULT_QOA_VALUE = 0.5
DEFAULT_QOA_METHOD = "blending_formula"
DEFAULT_EVAL_CACHING = True

# Optimization Features
DEFAULT_CANONICALIZATION = True
DEFAULT_HISTORY_INDEXING = True
DEFAULT_PARALLEL_ENABLED = False
DEFAULT_PARALLEL_WORKERS = 4

# Validation
DEFAULT_BLEND_CONSTRAINTS = True
DEFAULT_DAG_VALIDITY = True
DEFAULT_STRICT_MODE = True

# Output Configuration
DEFAULT_OUTPUT_DIR = "results"
DEFAULT_CSV_OUTPUT = True
DEFAULT_JSON_OUTPUT = True
DEFAULT_PICKLE_OUTPUT = False
DEFAULT_VIZ_ENABLED = True
DEFAULT_VIZ_FORMAT = "png"
DEFAULT_SAVE_INTERMEDIATE = False

# Debug Configuration
DEFAULT_VERBOSE = True
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_PROFILING = False
DEFAULT_TRACE_EVAL = False

# Reproducibility
DEFAULT_RANDOM_SEED = 42
DEFAULT_DETERMINISTIC = True

# Small epsilon for floating point comparisons
EPS = 1e-9
